# Generated by Django 5.2 on 2025-06-13 23:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('installation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte_question', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('date_signalisation', models.DateTimeField(auto_now_add=True)),
                ('installation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='installation.installation')),
            ],
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solution_proposee', models.TextField()),
                ('cout_estime', models.DecimalField(decimal_places=2, max_digits=12)),
                ('temps_estime_heure', models.PositiveIntegerField()),
                ('date_intervention', models.DateTimeField(blank=True, null=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenances', to='maintenance.incident')),
            ],
        ),
        migrations.CreateModel(
            name='ReponseMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reponse', models.TextField()),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='maintenance.incident')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintenance.questionmaintenance')),
            ],
        ),
    ]
