# Generated by Django 5.2 on 2025-06-13 23:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Devis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cout_achat', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cout_installation', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cout_maintenance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Installation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consommation_energetique', models.DecimalField(decimal_places=2, max_digits=12)),
                ('province', models.CharField(max_length=100)),
                ('option_stockage', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='InstallationEquipement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='SchemaInstallation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier_schema', models.FileField(blank=True, null=True, upload_to='schemas/')),
            ],
        ),
        migrations.CreateModel(
            name='ComparaisonEconomique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cout_electricite_traditionnelle', models.DecimalField(decimal_places=2, max_digits=12)),
                ('economies_potentielles', models.DecimalField(decimal_places=2, max_digits=12)),
                ('duree_retour_investissement', models.PositiveIntegerField(help_text='Durée en années')),
                ('devis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comparaison', to='installation.devis')),
            ],
        ),
    ]
