# Generated by Django 5.2 on 2025-06-13 23:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boutique', '0002_initial'),
        ('installation', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='installation',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installations', to='user.profilclient'),
        ),
        migrations.AddField(
            model_name='installation',
            name='technicien',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='installations', to='user.profiltechnicien'),
        ),
        migrations.AddField(
            model_name='devis',
            name='installation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='devis', to='installation.installation'),
        ),
        migrations.AddField(
            model_name='installationequipement',
            name='equipement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boutique.equipement'),
        ),
        migrations.AddField(
            model_name='installationequipement',
            name='installation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='installation.installation'),
        ),
        migrations.AddField(
            model_name='installation',
            name='equipements',
            field=models.ManyToManyField(through='installation.InstallationEquipement', to='boutique.equipement'),
        ),
        migrations.AddField(
            model_name='schemainstallation',
            name='installation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schema', to='installation.installation'),
        ),
    ]
