# Generated by Django 5.2 on 2025-06-13 23:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boutique', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boutique',
            name='commercant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boutiques', to='user.profilcommercant'),
        ),
        migrations.AddField(
            model_name='equipement',
            name='boutique',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipements', to='boutique.boutique'),
        ),
        migrations.AddField(
            model_name='equipementimage',
            name='equipement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='boutique.equipement'),
        ),
        migrations.AddField(
            model_name='equipement',
            name='marque',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='boutique.marque'),
        ),
        migrations.AddField(
            model_name='typeequipement',
            name='specifications',
            field=models.ManyToManyField(to='boutique.specification'),
        ),
        migrations.AddField(
            model_name='equipement',
            name='type_equipement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boutique.typeequipement'),
        ),
    ]
